### PR TITLE
Added Responsive Footer

### PR DESCRIPTION
**Pull request by Prabhsingh0401**
A Responsive Footer for all devices.

Can be used for any webpage.

### CODE REVIEW

**Review by aayush105 — COMMENTED** [review]
@Prabhsingh0401 Add the output in the image section as well as in README.md file. And if its different then login/signup page you can make another folder for it and push it.

**Comment by Prabhsingh0401** [comment]
On it !

**Comment by Prabhsingh0401** [comment]
Hey did all the respective changes you can check it out : )

**Review by aayush105 — APPROVED** [review]
LGTM!
Thank you @Prabhsingh0401 for contributing.

**Pull request merged**
