### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by yaxit24**
1. Added a rotating shadow overlay for a realistic lighting effect on the earth.
2. Introduced a day-night cycle animation to simulate light movement across the globe.

### CODE REVIEW

**Comment by aayush105** [comment]
Show the output.

**Comment by yaxit24** [comment]
please wait, let me find my code.

**Comment by yaxit24** [comment]
here is the recording:  https://www.icloud.com/notes/04aavFJHzItsflmz3842NT5zg#Saved_Video

**Comment by yaxit24** [comment]
please review my changes as soon as possible.

**Comment by yaxit24** [comment]
please let me know if any further changes are need to be made.

**Comment by aayush105** [comment]
Please upload the output image.

**Comment by V1vekW** [comment]
output image by  [@yakshit
](https://github.com/yaxit24)

https://github.com/user-attachments/assets/e109bdff-9a72-475b-be1c-c5143cb087da

**Comment by yaxit24** [comment]
Thank you so much for accepting my proposed changes! I’m thrilled to know that my contributions could add value to the project. Your feedback and collaboration make all the difference, and I’m excited to continue working together to make this even better. Thanks again for your support — looking forward to the next steps!

**Pull request merged**
