### PR TITLE
Analog Calendar Using HTML and CSS

### PR DESCRIPTION
**Pull request by VipulNerd**
This is an analog calendar built using HTML and CSS. It's Fully functional. You can check the real-time date and also scroll back to the previous year and month. On the other hand, you can scroll to the next month and year.Below are some images regarding its working.

Screenshot 2024-10-09 at 8 57 32 AM

Screenshot 2024-10-09 at 8 57 47 AM

Screenshot 2024-10-09 at 8 57 58 AM

Screenshot 2024-10-09 at 8 58 06 AM

### CODE REVIEW

**Comment by VipulNerd** [comment]
@aayush105 I have created the Analog Calendar as assigned by you. Please try to review it and if it feels correct, Please accept the PR.
Thank you.

**Review by aayush105 — COMMENTED** [review]
Can you add the output images which you have added in the description to your calendar folder as well?

**Review by aayush105 — APPROVED** [review]
Great work @VipulNerd. Keep contributing.

**Comment by aayush105** [comment]
> Can you please add the Hacktoberfest-accepted or Hacktoberfest label to this PR.

Done @VipulNerd

**Comment by VipulNerd** [comment]
Thanks

**Pull request merged**
