### PR TITLE
Added cursor types

### PR DESCRIPTION
**Pull request by ZoeADavis**
Issue #427 

Added Auto, Default, crosshair, wait, and text cursor types.

### CODE REVIEW

**Review by aayush105 — COMMENTED** [review]
@ZoeADavis can you add the screenshot of the output in the description section so that i can go through it and merge your PR.

**Comment by ZoeADavis** [comment]
@aayush105 
output

**Comment by aayush105** [comment]
> @aayush105 output

Can you just improvise your plain html text to some thing else using CSS or icons?
As the plain text doesn't look cool, so if you can please add the some sort of flex to the various hover cursor buttons, add icons in front of plain text, animated buttons. These are my suggestions so that you can improve your skill.

**Comment by ZoeADavis** [comment]
@aayush105 
image_2024-10-02_193739519

**Comment by ZoeADavis** [comment]
@aayush105 

image_2024-10-02_194737003

updated and added icons, flex, and transition animations when you over over it.

**Review by aayush105 — APPROVED** [review]
Great work @ZoeADavis

**Pull request merged**
