### PR TITLE
Updated landing page

### PR DESCRIPTION
**Pull request by ArjunCodess**
Reorganized and updated content and projects, improved layout, added categories for better user experience and made the landing page responsive.

## Changes
- Reorganized content into categories: 3D and Animations, CSS Art, Layout and Components, Websites and Projects, Miscellaneous, Examples, V2, Misc, and Other
- Improved table layout for better readability
- Added new dark/light mode toggle button with better styling
- Added new "working" to various CSS examples and projects
- Improved responsive design for mobile devices
- ***Major Change:*** Added all the new projects recently merged to the repo.

Demo Image and Video:
image
image
https://github.com/user-attachments/assets/8f02b6f7-4d16-43b1-bb81-5b0825028fe8

Please review and let me know if any further changes are needed.

### CODE REVIEW

**Review by aayush105 — APPROVED** [review]
Great work !!
Finally after a lot of PR conflict, now able to merge your contribution. @ArjunCodess

**Comment by ArjunCodess** [comment]
My pleasure, Aayush! Thanks for the opportunity.

**Comment by ArjunCodess** [comment]
For the repo structure and all, can you ask your next contributors to list their projects in the index.html in the correct category while submitting a PR?

You can also guide them on how to do that as this would be great for maintaining the project.

**Comment by aayush105** [comment]
> For the repo structure and all, can you ask your next contributors to list their projects in the index.html in the correct category while submitting a PR?
> 
> You can also guide them on how to do that as this would be great for maintaining the project.


Here’s the updated version of your response incorporating the additional point:

@ArjunCodess 
Thank you for the suggestion regarding updating the **index.html** for contributor projects. However, implementing changes in **index.html** may lead to conflicts across multiple contributors' submissions, which could complicate the merging process.

Previously, you also encountered similar conflicts in **index.html** due to the same reason.

To resolve this, it’s important that all contributors always pull the latest changes from the main branch before creating a PR. This approach will help avoid conflicts and keep the codebase in sync.

In addition, I recommend having one contributor take the lead in creating a PR to establish and maintain the structure of the landing page. This will further minimize conflicts and ensure all projects are categorized consistently.

Once the structure is in place, future contributors can list their projects under the appropriate sections in index.html when submitting their PRs.

Let me know if you have any thoughts or suggestions on this approach!

**Comment by ArjunCodess** [comment]
Well, I'm in to keep the landing page updated. Can update it every month or two, sounds good?

**Comment by aayush105** [comment]
> Well, I'm in to keep the landing page updated. Can update it every month or two, sounds good?

You can do it in oct month only as this repo is more active on the oct month, so you can do on every 5 days in oct month else in 2 months or more.

**Comment by ArjunCodess** [comment]
Oh, yes. Great! I'll get back to you in like - 5 days.

**Comment by aayush105** [comment]
> Oh, yes. Great! I'll get back to you in like - 5 days.

Ok sure @ArjunCodess

**Pull request merged**
