### PR TITLE
Add Scroll-Unblur-Text-Effect and Scroll-Video-Animation components. …

### PR DESCRIPTION
**Pull request by ArjunCodess**
…Update landing page with better styles and categorise them into groups.

---

Below is a breakdown of the changes introduced in this pull request:

This pull request introduces two new interactive components and improves the landing page design:

---

### 1. Scroll-Unblur Text Effect (/Scroll-Unblur-Text-Effect):

Adds a new component that gradually reveals and unblurs text as the user scrolls.

Implemented using scroll-linked animations.

### 2. Scroll Video Animation (/Scroll-Video-Animation):

Introduces a video masking effect that responds to scroll position.

Uses SVG paths for creative masking of video content.

### 3. Landing Page Enhancements:

Improved description text to better explain the purpose of the site.

Updated styling.

Categorized the components into clear groups.

---

Please let me know if any changes or updates are needed, and I’ll be happy to address them.

~ ArjunCodess

### CODE REVIEW

**Review by aayush105 — COMMENTED** [review]
@ArjunCodess can you provide the before and after demo video of the changes you have made?

**Comment by ArjunCodess** [comment]
The conflict lies in the landing page, I have tried to style it better. Is there any problem with that?

image

---

Yes, this is the demo video:

https://github.com/user-attachments/assets/662ce8b2-4e26-42b9-bd99-681041742c5c

**Comment by aayush105** [comment]
> The conflict lies in the landing page, I have tried to style it better. Is there any problem with that?
> 
> image
> Yes, this is the demo video:
> 
>  2024-10-03.23-23-27.mp4

No, there isn't any problem making a better style, your work is awesome.  To merge your PR the conflict must be resolved by you, in order to resolve it you can check it on google else you can make the copy of the files you have added and then:

- Go to your forked repository in your local and you will see a sync fork click there and update the branch
- Then go to the pull the main branch in your local and then make the necessary changes you have done in the index.html and other files
- And then push the commit to the same branch which you had previously pushed.

**Comment by ArjunCodess** [comment]
So, I have to basically -

1. Sync My Fork and Pull Changes
2. Resolve Conflicts
3. Commit and Push.

So, I have to resolve this conflict by reverting to the previous landing page, right?

Okay, got it.

**Comment by ArjunCodess** [comment]
Hey! Sorry for that. But I have done all the stuff.

Reverted back to the original landing page, so no conflicts with the base branch.

**Comment by aayush105** [comment]
> Hey! Sorry for that. But I have done all the stuff.
> 
> Reverted back to the original landing page, so no conflicts with the base branch.

But the landing page was looking cool in the demo video, so can you make the new PR for that again? Like i will merge this PR and then you update your branch locally and pull the origin main and then make the changes in index.html landing page and then create a new branch and make the new PR. Also if you can more improve the style and layout of the landing page then you can make changes and upload the demo video or image in the description.
@ArjunCodess

**Pull request merged**
