### PR TITLE
Added Profile Cards

### PR DESCRIPTION
**Pull request by pravin435916**
2 profile cards added

### CODE REVIEW

**Review by aayush105 — COMMENTED** [review]
@pravin435916 can you provide the output image in the description? so that it will be easy to go through it and merge your PR.

**Comment by pravin435916** [comment]
sure 
p1
p2

 i added currently two card if you like this ill add more after merging ill create another issue and add it to it . Thank you :)

**Review by aayush105 — APPROVED** [review]
Awesome work @pravin435916. 
But if you are creating the other PR then please add the image in the README.md file as well and also in description.

**Comment by pravin435916** [comment]
> Awesome work @pravin435916. 
> But if you are creating the other PR then please add the image in the README.md file as well and also in description. And if you are going to create the card again then please make a Card folder and add all the card design files under the same folder.

Sure 😊 thank you :)

**Pull request merged**
