### PR TITLE
Added a music player template

### PR DESCRIPTION
**Pull request by Ashu-tosh1**
I have  added music player template  built using HTML and CSS. I have also added some transition and hover effects. Below are some images regarding its working.

Screenshot 2024-10-09 210903

Screenshot 2024-10-09 210917

Screenshot 2024-10-09 210927

### CODE REVIEW

**Comment by Ashu-tosh1** [comment]
@aayush105 I have created the task  assigned by you. Please try to review it and if it feels correct, Please accept the PR.
Thank you. Please add the label hacktoberfest after approving my PR.

**Review by aayush105 — COMMENTED** [review]
Awesome work. Best PR as of now !!! @Ashu-tosh1 

Also , I want you to add the output images under the images folder as well or make the new Output folder under the Music folder and add the output images which will make user easier.

**Comment by Ashu-tosh1** [comment]
@aayush105 okay i will do that..

**Comment by Ashu-tosh1** [comment]
@aayush105 the changes that you suggested has been done. Please approve this PR and add label of hacktoberfest.

**Comment by aayush105** [comment]
> @aayush105 the changes that you suggested has been done. Please approve this PR and add label of hacktoberfest.

I wanted you to add the output images which you have provided above also to be included in your folder. @Ashu-tosh1

**Comment by Ashu-tosh1** [comment]
@aayush105  ya i have added that images, now please check it once.

**Review by aayush105 — APPROVED** [review]
Awesome work !! @Ashu-tosh1

**Comment by Ashu-tosh1** [comment]
@aayush105 thank you! I can solve other issues also or add some new project. You can assign me.

**Comment by aayush105** [comment]
> @aayush105 thank you! I can solve other issues also or add some new project. You can assign me.

Yes you can create issue, mention me and i will assign you then you can work on it.
@Ashu-tosh1

**Pull request merged**
