### PR TITLE
Added an Animation Box

### PR DESCRIPTION
**Pull request by Ayansaxena24**
HTML and CSS working Link -> https://codepen.io/Ayan-Saxena/pen/qBgBYoZ
Please approve this for Hacktoberfest 2023. I have updated the readme file too.

### CODE REVIEW

**Review by aayush105 — COMMENTED** [review]
@Ayansaxena24 why you have uploadthe the multiple README files duplicate please fix it and push it again.

**Review by gaurovgiri — APPROVED** [review]
LGTM

**Comment by Ayansaxena24** [comment]
hey @aayush105 @gaurovgiri  !
I have removed the multiple versions of README files. Can you please review and merge this PR?

**Review by aayush105 — APPROVED** [review]
LGTM!
Thank you for your contribution @Ayansaxena24 .

**Pull request merged**
