### PR TITLE
Create retro background

### PR DESCRIPTION
**Pull request by Anshgupta0123**

### CODE REVIEW

**Review by aayush105 — COMMENTED** [review]
@Anshgupta0123 can you provide the video sample of your project and add it in the image section as well as in README.md file.

**Comment by Anshgupta0123** [comment]
https://github.com/you-dont-need/You-Dont-Need-JavaScript/assets/123660724/c5d38616-a9df-4f8e-840e-83e9620ef7ab

**Comment by Anshgupta0123** [comment]
this is the video sample of my retro style background

**Review by aayush105 — COMMENTED** [review]
LGTM! 
Thank you @Anshgupta0123  for contributing.

**Pull request merged**
