### PR TITLE
Modified Pendulum, added oscillaation speed control slider

### PR DESCRIPTION
**Pull request by Shocker-lov-t**
Modified The existing HTML and CSS files to look it more good
added a Slider using Javascript, to control the Oscillation speed of pendulum

### CODE REVIEW

**Review by aayush105 — COMMENTED** [review]
JavaScript is not allowed to use in this repository. Try doing projects using only HTML and CSS.

**Review by gaurovgiri — CHANGES_REQUESTED** [review]
This PR will get approve once you remove the script part, everything else seems improvement.

**Comment by Shocker-lov-t** [comment]
> This PR will get approved once you remove the script part, everything else seems improvement.

Done

**Comment by aayush105** [comment]
> > This PR will get approved once you remove the script part, everything else seems improvement.
> 
> Done

You only have added in the quick link section, add the output as well in images section and add the url in the README.md file.

**Review by aayush105 — APPROVED** [review]
LGTM!
Thank you @Shocker-lov-t for your contribution.

**Review by Shocker-lov-t — COMMENTED** [review]
Updated the Readme file
Uploaded the demo in image
Removed JS

**Pull request merged**
