### PR TITLE
solved the issue of black light persistence

### PR DESCRIPTION
**Pull request by Sonu0305**
#547 i added a check box to ensure that when the check box is ticked it remains in the dark mode and otherwise light mode so it helps user to navigate between pages and stilll be in dark mode

### CODE REVIEW

**Review by aayush105 — COMMENTED** [review]
Can you upload the demo video of the solved issue?
@Sonu0305

**Comment by Sonu0305** [comment]
> Can you upload the demo video of the solved issue? @Sonu0305

yes definitely, @aayush105 

https://github.com/user-attachments/assets/eb310752-5ace-49ea-9bb8-ba99432f4204

**Review by aayush105 — APPROVED** [review]
LGTM!! @Sonu0305

**Comment by Sonu0305** [comment]
> LGTM!! @Sonu0305

Thank you so much😄!!
@aayush105

**Pull request merged**
