### PR TITLE
Preethamprofile

### PR DESCRIPTION
**Pull request by daemonvk18**

### CODE REVIEW

**Review by gaurovgiri — COMMENTED** [review]
What is this? What is this file supposed to generate?

**Comment by daemonvk18** [comment]
it's just a basic portfolio home page

**Review by gaurovgiri — APPROVED** [review]
Seems good to me!

**Comment by daemonvk18** [comment]
Thank you

**Review by aayush105 — APPROVED** [review]
Thank you @daemonvk18 for conributing and keep contributing in the repository & @gaurovgiri  for your review.

**Pull request merged**
