### PR TITLE
Chore: Updated README with github badges

### PR DESCRIPTION
**Pull request by SusheelThapa**

### CODE REVIEW

**Comment by SusheelThapa** [comment]
This PR solves #178 issue.

**Review by malivinayak — CHANGES_REQUESTED** [review]
@stevemao 
I just reviewed the PR made by @SusheelThapa 
The License badge should be updated i.e. custom made 
image

**Comment by SusheelThapa** [comment]
@malivinayak The license of the repo is given below:
image

And above license isn't standard license of github so it is not identified.

And I am already raised issue regarding License #188

**Comment by malivinayak** [comment]
> I am already raised issue regarding License #188

I don't have any issue with your PR
Just submitting PR review as this is open source contribution.

**Review by stevemao — APPROVED** [review]
Thanks

**Comment by stevemao** [comment]
Can you please resolve the conflicts?

**Comment by SusheelThapa** [comment]
@stevemao I don't have write permission to resolve the conflict.

**Comment by stevemao** [comment]
You don't have write permission to your own repo?

**Pull request closed without merging**
