### PR TITLE
feat: Create an infinite image carousel

### PR DESCRIPTION
**Pull request by purnasth**
# Pull Request Title: Addition of Infinite Carousel Project

## Pull Request Description:
I have added the `Infinite Image Carousel` project to the **You-Dont-Need-JavaScript** repository. This project features an infinite carousel implemented using HTML and CSS, providing a lightweight alternative to JavaScript-based carousels.

## Attachments 

Infinite-carousel-purnasth

### CODE REVIEW

**Review by aayush105 — COMMENTED** [review]
@purnasth can you add the .gif in the image section and as well as in README.md file.

**Comment by purnasth** [comment]
I'm doing it now and will commit to it very soon. @aayush105

**Comment by purnasth** [comment]
Hello, @aayush105 the gif has finally been added to the PR on e37b14611281b8d4f26a7d56a760950ca6cc0896 commit and is ready to be merged.

**Review by aayush105 — APPROVED** [review]
LGTM!
Thank you @purnasth for contributing. Keep contributing!!!

**Pull request merged**
