### PR TITLE
cardanima

### PR DESCRIPTION
**Pull request by SOUMYADEP**
I have made a card animation using only html and css .

# screenshot
chrome-capture-2023-9-20

### CODE REVIEW

**Review by aayush105 — APPROVED** [review]
Nice work.

**Review by aayush105 — APPROVED** [review]
Can you please provide the video sample ? so that we can easly merge your PR.

**Comment by SOUMYADEP** [comment]
@aayush105 , Sir , I have added the req screenshot , please give it a review and merge it .

**Comment by aayush105** [comment]
> @aayush105 , Sir , I have added the req screenshot , please give it a review and merge it .

Please add the image in README.md file as well, firstly pull the updated repository and then push it again.

**Review by gaurovgiri — APPROVED** [review]
LGTM, thanks for the contribution

**Review by aayush105 — APPROVED** [review]
LGTM!
Thank you @SOUMYADEP for contributing

**Pull request merged**
