### PR TITLE
Thankyou-animation

### PR DESCRIPTION
**Pull request by Ankit-3130**
added a Thankyou animation 
Demo

### CODE REVIEW

**Comment by aayush105** [comment]
Please add the image in README.md file as well.

**Comment by Ankit-3130** [comment]
> Please add the image in README.md file as well.

added image in README.md file

**Comment by aayush105** [comment]
> > Please add the image in README.md file as well.
> 
> added image in README.md file
Ok I will merge it.

**Comment by aayush105** [comment]
> > Please add the image in README.md file as well.
> 
> added image in README.md file

OK i will check and merge it.

**Review by aayush105 — APPROVED** [review]
Thank you for contributing @Ankit-3130. keep contributing and fixing issues.

**Pull request merged**
