### PR TITLE
Added:More profile Cards and Updated Readme.MD

### PR DESCRIPTION
**Pull request by pravin435916**
Things i added and in more structured formats.
**/ProfileCards** 
   /card1
   /card2
  /card3
  /card4
  /card5
  /card6
with their proper html csss
Updated readme.MD with screenshot and links as per u said previously ,

### CODE REVIEW

**Comment by kalilinux-png** [comment]
Look's Great 👍🏻

**Review by aayush105 — COMMENTED** [review]
@pravin435916 the cards are great, but there is a conflict in the README.md file. so, can you resolve it and commit again?

**Comment by pravin435916** [comment]
@aayush105 i resolved it . can you merge it now

**Review by aayush105 — APPROVED** [review]

**Comment by aayush105** [comment]
> @aayush105 i resolved it . can you merge it now

Sure @pravin435916, I will merge it.

**Pull request merged**
