### PR TITLE
Adding Background color and modify hover effect in About us Button

### PR DESCRIPTION
**Pull request by Mrigendra1-Singh**

### CODE REVIEW

**Review by aayush105 — APPROVED** [review]
Can you please provide the video sample ?

**Review by gaurovgiri — COMMENTED** [review]
Can you provide before and after changes image ?

**Review by gaurovgiri — APPROVED** [review]
I think, it can be merged!

**Comment by aayush105** [comment]
> LGTM, thanks for the contribution

ok @gaurovgiri, I will merge this then with you review.

**Pull request merged**
