### PR TITLE
flip-animated circle

### PR DESCRIPTION
**Pull request by aishrani**
flip animated circle by using HTML and CSS. #158 

[screen-capture (2).webm](https://github.com/you-dont-need/You-Dont-Need-JavaScript/assets/45910254/e4bdb21e-32d6-4cc5-8d88-7007598cd386)

### CODE REVIEW

**Review by aayush105 — COMMENTED** [review]
@aishrani add the video sample/ image in the image section as well as in README.md file.

**Comment by aishrani** [comment]
@aayush105 I added the image in the image section as well as in README.md file.

**Review by gaurovgiri — APPROVED** [review]
LGTM

**Review by aayush105 — APPROVED** [review]
Thank you @aishrani for contributing and @gaurovgiri for you review.

**Pull request merged**
