### PR TITLE
Basic structure completed and button 2 variants ready

### PR DESCRIPTION
**Pull request by muditkashyap**
I'll create a documentation for this and more button varient first
For this I can't provide video now because it's structure work.

like User first have to add base.css file it's compulsary. What it's doing, I've added in code comment.

Next we'll have seprate files for all component type like buttons.html, cards.html

buttons.html will contain all button design, simple, animated and all not diff file, and it'll have same practise like to add color bg we have pre-defined classes just use that, same for add radius in button, same for hover, same for neon effect and using the class it'll make perfect design and working button. this repository will work like library than.

Working on #254

### CODE REVIEW

**Review by aayush105 — COMMENTED** [review]
Great work @muditkashyap  and I have assigned the issue to you. Keep working and fixing issues.

**Review by aayush105 — APPROVED** [review]
Thank you for Contributing @muditkashyap .

**Comment by muditkashyap** [comment]
@aayush105  Thank you for appreciation, This issue will take little longer time and will be multiple PR for same. And after 2-3 PR. We have to create a new branch we can give some name like "stable" "version" or whatever you decide so new structure and all guidelines, we'll manage there.

I am making this contribution for learning and mentain this, can I get a follow back. If you don't mind?

**Comment by aayush105** [comment]
> @aayush105  Thank you for appreciation, This issue will take little longer time and will be multiple PR for same. And after 2-3 PR. We have to create a new branch we can give some name like "stable" "version" or whatever you decide so new structure and all guidelines, we'll manage there.
> 
> I am making this contribution for learning and mentain this, can I get a follow back. If you don't mind?

Appreciate your hard work @muditkashyap. You can maintain on your own I ill review it and merge it. And surely you will get follow back, just follow.

**Pull request merged**
