### PR TITLE
Changed the Styling so that it is well known to the user that it is clickable

### PR DESCRIPTION
**Pull request by devrupchowdhury**
Border Addition to Clickable Header:

1.Added a visible border to the clickable header for better distinction and improved user experience.
The border enhances the visual separation between sections and makes the header's clickable nature more apparent.
Added JavaScript SVG Icon:

2.Included an SVG of the JavaScript logo for a more visually appealing representation.
The SVG is optimized for performance and integrated into the appropriate section for seamless display.

These changes aim to improve the interface's usability and visual aesthetics.

### CODE REVIEW

**Comment by aayush105** [comment]
Provide me the output of your code.

**Comment by devrupchowdhury** [comment]
Screenshot 2024-10-24 125859
This is the output

**Comment by aayush105** [comment]
> Screenshot 2024-10-24 125859 This is the output

the icon and the title is not aligned perfectly make it aligned.

**Comment by devrupchowdhury** [comment]
Screenshot 2024-10-24 125859
Done!!

**Comment by devrupchowdhury** [comment]
Screenshot 2024-10-24 125859
Done!!

**Comment by devrupchowdhury** [comment]
Screenshot 2024-10-24 125859
Done!!

**Comment by devrupchowdhury** [comment]
I have perfectly aligned it .

**Comment by aayush105** [comment]
> I have perfectly aligned it .

OK nice one

**Pull request merged**
