### PR TITLE
Card show component

### PR DESCRIPTION
**Pull request by Sooryaprabhath**
I added new HTML and CSS-based card component UI.

### CODE REVIEW

**Review by aayush105 — COMMENTED** [review]
@Sooryaprabhath you also need to add the output of your image in the README.md file and in the description so that i can go through it.

**Comment by Sooryaprabhath** [comment]
> @Sooryaprabhath you also need to add the output of your image in the README.md file and in the description so that i can go through it.

I added image.

**Comment by aayush105** [comment]
> > @Sooryaprabhath you also need to add the output of your image in the README.md file and in the description so that i can go through it.
> 
> I added image.

There is conflict in the README.md and index.html file can you fix that so that i will be able to merge it.

**Comment by Sooryaprabhath** [comment]
Resolved check now

**Comment by aayush105** [comment]
> Resolved check now

There is still a conflict in same files, can you check it once again. @Sooryaprabhath

**Comment by Sooryaprabhath** [comment]
I will re-do pull req ig some changes are been merged before mine in the same line

**Comment by aayush105** [comment]
> I will re-do pull req ig some changes are been merged before mine in the same line

still there is a conflict @Sooryaprabhath Close the PR and then update you branch 1st and then pull the changes then update your changes and create a PR again.

**Pull request closed without merging**
