### PR TITLE
Fixing the Issue with the Portfolio Website

### PR DESCRIPTION
**Pull request by drainbadenergy**
Before, I start with the fix, I would like to mention that I found JavaScript code on the Port.html file.

Here are the issues I fixed, for the raised Issue #519  :

- I fixed the website to have a neutral look by replacing the name with John Doe.
- Enlarged the image on the page.
- Made the buttons look more appealing.
- Made the Icons of the companies bigger and appealing.
- Fixed typos/spelling errors.
- Also removed the <script> code😝 

Screenshot of the updated webpage look
image

[✅] I have performed a self-review of my code.

[✅] I ran the app and tested it locally to verify that it works as expected.

[✅] I have checked my code with an automatic accessibility tool and it shows no errors.

Kindly let me know if there is something I have to change/adjust with the code! @aayush105

### CODE REVIEW

**Review by aayush105 — COMMENTED** [review]
Can you add the output image in the Portfoliowebiste folder itself? so that it will be easier to look the output of the code.

**Comment by drainbadenergy** [comment]
Hey @aayush105, I have added the output image in the folder! Please let me know, if there's something else I could change.

**Review by aayush105 — APPROVED** [review]
Awesome work. @drainbadenergy

**Comment by drainbadenergy** [comment]
Thank you very much!

**Pull request merged**
