### PR TITLE
dog-box-animation

### PR DESCRIPTION
**Pull request by Ankit-3130**
this is a dog box animation using only HTML and CSS.
demo link:
demo link

### CODE REVIEW

**Review by aayush105 — COMMENTED** [review]
Add the image into the README.md as well.

**Comment by Ankit-3130** [comment]
added the image into README.md

**Comment by aayush105** [comment]
> added the image into README.md

Ok i will check it and merge it.

**Review by aayush105 — APPROVED** [review]
Thank you for contributing @Ankit-3130 .

**Pull request merged**
