### PR TITLE
floating label pure css

### PR DESCRIPTION
**Pull request by muditkashyap**
sovled #60 

https://github.com/you-dont-need/You-Dont-Need-JavaScript/assets/45191575/6898fb0b-edc3-4226-84de-f567088a549e

In this issue: we required only floating label css, so i've not focused on design form, I've just added css for label to design required result.

### CODE REVIEW

**Comment by aayush105** [comment]
Nice work. keep working on css more.

**Review by aayush105 — APPROVED** [review]
Thank you @muditkashyap for contributing and keep contributing.

**Comment by muditkashyap** [comment]
@aayush105 Thank you for aapreciate my contribution, Soon I'll make more updates, But I am having few suggestion for this repo. Currently we are making everything in same example folder and internal CSS, but instead of this We can make contribution guidelines and can make a fresh structure for file we can make complete own library where everthing should be well documented and in proper format like we can have multiple design for carousel, cards and other stuff and I've checked some code that was completed copy, I think project moderator should take care of it.

**Comment by aayush105** [comment]
> @aayush105 Thank you for aapreciate my contribution, Soon I'll make more updates, But I am having few suggestion for this repo. Currently we are making everything in same example folder and internal CSS, but instead of this We can make contribution guidelines and can make a fresh structure for file we can make complete own library where everthing should be well documented and in proper format like we can have multiple design for carousel, cards and other stuff and I've checked some code that was completed copy, I think project moderator should take care of it.

@muditkashyap you can just create folder that you have mentioned under the same example folder and structure the files if you want to contribute on this issue. Create a issue and then work on it and then create a PR.

**Comment by muditkashyap** [comment]
ok sure.

**Pull request merged**
