### PR TITLE
Neon hover effect

### PR DESCRIPTION
**Pull request by NoorulAinAga**
solved #158 
[screen-capture.webm](https://github.com/you-dont-need/You-Dont-Need-JavaScript/assets/93398177/f9e5633e-cd58-4619-817b-190bbdd18c5e)

### CODE REVIEW

**Comment by aayush105** [comment]
Provide the video sample of your code.

**Comment by NoorulAinAga** [comment]
> Provide the video sample of your code.

I have updated PR description  with screen recording of my code output

**Comment by aayush105** [comment]
> > Provide the video sample of your code.
> 
> I have updated PR description with screen recording of my code output

Nice work and keep working.

**Review by aayush105 — APPROVED** [review]
Thank you for contributing @NoorulAinAga. Keep contributing.

**Pull request merged**
