### PR TITLE
GIF responsive Navbar #346

### PR DESCRIPTION
**Pull request by parthasdey2304**
Added the GIF for the responsive Navbar with sidebar in phone screens!!

### CODE REVIEW

**Review by gaurovgiri — APPROVED** [review]
LGTM

**Review by aayush105 — APPROVED** [review]
LGTM!
Thank you @parthasdey2304 for contributing

**Comment by parthasdey2304** [comment]
@aayush105 man please check your GitHub readme issues.... I have raised an issue for your GitHub's README.md file regarding the icons...

**Comment by aayush105** [comment]
> @aayush105 man please check your GitHub readme issues.... I have raised an issue for your GitHub's README.md file regarding the icons...

Yess i saw it and i jave replied your issue.

**Pull request merged**
