### PR TITLE
Fix Issue #346

### PR DESCRIPTION
**Pull request by parthasdey2304**
Added a responsive Navbar with sidebar for smaller screens!!

### CODE REVIEW

**Review by aayush105 — COMMENTED** [review]
@parthasdey2304 can you provide the output of before and after?

**Comment by parthasdey2304** [comment]
@aayush105 Check this out meanwhile i am adding the images to the images directory in the second PR : https://drive.google.com/file/d/1yxGrBc9_Clc_jA0S6ehpsDLz0qrRpDvp/view?usp=sharing

**Comment by parthasdey2304** [comment]
@aayush105 Please merge both of the PRs

**Review by gaurovgiri — APPROVED** [review]
LGTM, thanks for the contribution

**Comment by aayush105** [comment]
LGTM!
Thank you @parthasdey2304 for contributing.

**Review by aayush105 — APPROVED** [review]
LGTM!
Thank you @parthasdey2304 for contributing

**Pull request merged**
