### PR TITLE
Add a Coffee Machine Animation

### PR DESCRIPTION
**Pull request by Zemerik**
## Changes:

- Added a Coffee Machine Animation
- Updated the `README.md` with the styling guide

Thanks for Reviewing

### CODE REVIEW

**Review by aayush105 — COMMENTED** [review]
@Zemerik there is conflict in the README.md file so, solve the conflict if you know to solve else  don't include your output  in the README.md file instead add you output demo video in the description.

**Comment by Zemerik** [comment]
Hey @aayush105 , 

Thanks for taking the time to review my PR. 

I am a bit confused with what the conflict is, can you elaborate a little more?

**Comment by aayush105** [comment]
> Hey @aayush105 ,
> 
> Thanks for taking the time to review my PR.
> 
> I am a bit confused with what the conflict is, can you elaborate a little more?

I wanted to clarify the conflict in the README.md file. It seems that you've added your output PNG image to the README.md, but other contributors have also updated this file with their output images. Since you haven't updated your branch with the latest changes from the main branch, this has led to the conflict.

To resolve this, you can either:

- Merge the latest changes from the main branch into your branch and update the README.md accordingly.
- Alternatively, you can simply remove the code you added in the README.md file and commit your changes again in the same PR.

Let me know if you need any help!

**Comment by Zemerik** [comment]
Thank you. I have removed my changes in the README.md file, so my PR should be able to be merged now. 

If there are any more conflicts, let me know I will be happy to fix them!

- https://github.com/you-dont-need/You-Dont-Need-JavaScript/pull/508/commits/c2c0ed878070c7f4ff8095add86d30cc86977bfe

**Comment by aayush105** [comment]
> Thank you. I have removed my changes in the README.md file, so my PR should be able to be merged now.
> 
> If there are any more conflicts, let me know I will be happy to fix them!
> 
> * [c2c0ed8](https://github.com/you-dont-need/You-Dont-Need-JavaScript/commit/c2c0ed878070c7f4ff8095add86d30cc86977bfe)

image


you still have change in the README.md, like you can see that in the above image in line no: 145 there is a change, i think you have removed the - sign from there so also fix that. or else you can google it or use chat gpt to solve the conflict another way.

**Comment by Zemerik** [comment]
Hey, 

I think I have resolved that issue now. Any more Conflicts?

**Comment by aayush105** [comment]
> Hey,
> 
> I think I have resolved that issue now. Any more Conflicts?

Yes, you have finally made it. @Zemerik

**Comment by aayush105** [comment]
> Hey,
> 
> I think I have resolved that issue now. Any more Conflicts?

Hey, can you upload a demo video of your code here in the desciption?

**Comment by aayush105** [comment]
> > Hey,
> > I think I have resolved that issue now. Any more Conflicts?
> 
> Hey, can you upload a demo video of your code here in the description?

**Comment by Zemerik** [comment]
https://github.com/user-attachments/assets/fa815704-938d-484f-b973-746d2e2146d4

Here, also can you add the hacktoberfest label after you merge the pr?

**Review by aayush105 — APPROVED** [review]
Great work in animation @Zemerik. Keep working more and more.

**Comment by Zemerik** [comment]
Thank you for your help and taking the time to review to this pr!

**Pull request merged**
