### PR TITLE
Playing card

### PR DESCRIPTION
**Pull request by rohitmondal03**
Made a 3D moving card

### CODE REVIEW

**Review by aayush105 — COMMENTED** [review]
@rohitmondal03  please provide the sample video of your output in description as well as add in the README.md file.

**Comment by rohitmondal03** [comment]
https://github.com/you-dont-need/You-Dont-Need-JavaScript/assets/107113353/ee286098-7581-43ea-a9be-2cda8a19d1a4

**Comment by aayush105** [comment]
> playing-card-video.mp4

Add in README.md file as well.

**Comment by aayush105** [comment]
@rohitmondal03  Can you pull the new updates and resolve the conflict and push it again?

**Comment by aayush105** [comment]
@rohitmondal03  hello brother close this PR and the pull the updated repository and Create the PR again the problem of conflict will be solved.

**Pull request closed without merging**
