### PR TITLE
Cube image slider

### PR DESCRIPTION
**Pull request by rohitmondal03**
Made a cube image slider

### CODE REVIEW

**Review by aayush105 — COMMENTED** [review]
@rohitmondal03  please add a sample video in description and as well as in README.md file.

**Comment by rohitmondal03** [comment]
https://github.com/you-dont-need/You-Dont-Need-JavaScript/assets/107113353/db9c0534-7c34-47a8-aa96-ad1a4759a954

**Comment by rohitmondal03** [comment]
Why it is showing conflict in README.MD file  ?

**Comment by aayush105** [comment]
> Why it is showing conflict in README.MD file ?

Its README.md not README.MD. So fix this conflict and re create the PR.

**Comment by aayush105** [comment]
> Why it is showing conflict in README.MD file ?

@rohitmondal03  Can you pull the new updates and resolve the conflict and push it again?

**Comment by aayush105** [comment]
@rohitmondal03  hello brother close this PR and the pull the updated repository and Create the PR again the problem of conflict will be solved.

**Pull request closed without merging**
