### PR TITLE
fixed style guide issues

### PR DESCRIPTION
**Pull request by dennisboys**

### CODE REVIEW

**Comment by stevemao** [comment]
@dennisboys Can you add screenshots of before and after?

**Comment by dennisboys** [comment]
@stevemao What do you mean by screenshots of before and after? For this pull request I mainly set all images on the page to a height of "230" so to follow the style guide.

**Comment by stevemao** [comment]
Sorry, just to make it easier to review. something like [this](https://github.com/nodejs/nodejs.org/pull/654) if possible :)

**Comment by dennisboys** [comment]
@stevemao How about to make them gif? (Like the Twitter Heart Animation example on the page)

Since even using before/after static images, we cannot capture most of the CSS transition, which is the ultimate essence of these animations.

**Comment by stevemao** [comment]
@dennisboys sounds good :)

**Comment by stevemao** [comment]
what I was asking for is just to make it easier to review the PR. So that people don't have to pull your changes and see it locally. But animated gif in README sounds like a great idea :)

**Comment by dennisboys** [comment]
@stevemao Ah! Sorry for misunderstanding the before/after thing in the last couple of replies.

Here you go!

========== BEFORE ============

Some images were not set with a height of 230.
before

========== AFTER ============

Images were all set with a height of 230 (according to the style guide), so they look tidier on the page.
after

**Comment by dennisboys** [comment]
@stevemao Why this PR is not merged?

**Comment by dennisboys** [comment]
@stevemao @cht8687 Please let me know what need to be done for this PR as it is still not merged? As I said before, I plan to replace the current demo images with animated gifs after this merge.

**Comment by cht8687** [comment]
:+1:  @dennisboys

**Pull request merged**
