### PR TITLE
Update style.css

### PR DESCRIPTION
**Pull request by AbhishekKumarRay**
Added hover effect on button

### CODE REVIEW

**Review by aayush105 — COMMENTED** [review]
Provide the output of the code, if its existing code provide before and after output of the code. @AbhishekKumarRay

**Comment by AbhishekKumarRay** [comment]
Before
image


After
image


Added a hover effect on the arrow icon to make the icon look more beautiful.

**Review by aayush105 — APPROVED** [review]
LGTM!
Thank you @AbhishekKumarRay for contributing.

**Comment by AbhishekKumarRay** [comment]
Please give me Hacktoberfest label

**Pull request merged**
