### PR TITLE
Add CSS Transition

### PR DESCRIPTION
**Pull request by adikesava9706**

### CODE REVIEW

**Review by aayush105 — COMMENTED** [review]
@adikesava9706 button css is already there. so try to do new things.
Thank you !!!

**Comment by adikesava9706** [comment]
@aayush105 It is not button it is transition effect, in image it is showing like that check code

**Comment by aayush105** [comment]
> @aayush105 It is not button it is transition effect, in image it is showing like that check code

Provide the gif video sample and resolve the conflict as well @adikesava9706

**Comment by adikesava9706** [comment]
@aayush105 I changed code and created a gif and replaced

**Comment by aayush105** [comment]
> @aayush105 I changed code and created a gif and replaced

Hover transition is already there and still there is conflict in README.md file , to resolve it update your branch and pull the repo again and then push your code.

**Pull request closed without merging**
