### PR TITLE
replace static image with an animated gif for Fancy menu section

### PR DESCRIPTION
**Pull request by dennisboys**
I will replace all static images with animated gifs in the upcoming PR requests, section by section.

### CODE REVIEW

**Comment by cht8687** [comment]
thanks dennis. Why not combine them into one PR? As they are similar purpose-to make the screenshot dynamic.

**Comment by dennisboys** [comment]
My first thought was to break the task down into manageable bits so people can see changes incrementally, which is to embrace the essence of agile development. =)

But it's ok if you prefer to combine everything into one PR.

**Comment by cht8687** [comment]
Normally, when you make a PR, it means a feature. Since what you are doing is one purpose here, I think it's better to group them together as one PR. I am merging this PR though.

**Comment by dennisboys** [comment]
Ok, thanks for the clarification! I will make my PR feature-based in the future. =)

**Pull request merged**
