### PR TITLE
feature: Add new button style

### PR DESCRIPTION
**Pull request by HarshArora-1205**
Added new button with nice style: Rotating text on the surround, Animated arrow, And hover effects.
Documentation and codepen are properly linked.

[Documentation](https://github.com/HarshArora-1205/You-Dont-Need-JavaScript/blob/master/Button/Rotating-Text-w-Ripple/README.md)
[Codepen](https://codepen.io/harsharora1205/pen/ExqZEyw)

effect2

### CODE REVIEW

**Comment by HarshArora-1205** [comment]
Hi

Added new style. Feedbacks are welcomed.

**Comment by HarshArora-1205** [comment]
@aayush105 Can you review this?

**Comment by HarshArora-1205** [comment]
Awaiting confirmation.

**Comment by HarshArora-1205** [comment]
@aayush105 please review and merge the code

**Comment by aayush105** [comment]
Nice one

**Pull request merged**
