### PR TITLE
On-Off-switch.html

### PR DESCRIPTION
**Pull request by Dreadlord075**
Designed an on/off swtich based on html and css only
Sample Video:

https://github.com/you-dont-need/You-Dont-Need-JavaScript/assets/126400988/de4c94f0-f095-4769-8ec8-6d51b088816e

### CODE REVIEW

**Review by aayush105 — COMMENTED** [review]
@Dreadlord075  can you add image/video sample in the README.md .

**Comment by Dreadlord075** [comment]
Done.... Lemme know if i did it right

**Comment by Dreadlord075** [comment]
> @Dreadlord075 can you add image/video sample in the README.md .

* Done....Lemme know if i did it right

**Comment by Dreadlord075** [comment]
I added my previous merge samples in the readme.md file and images folder as well... please do check

**Review by aayush105 — APPROVED** [review]
Thank you for contributing @Dreadlord075 .

**Comment by aayush105** [comment]
> > @Dreadlord075 can you add image/video sample in the README.md .
> 
> * Done....Lemme know if i did it right

Yes you did it correct from now onward you can do all this while creating PR.

**Pull request merged**
