### PR TITLE
A simple Circular Progressive bar

### PR DESCRIPTION
**Pull request by gurramtejaswini**
Added output video

### CODE REVIEW

**Comment by aayush105** [comment]
> Hello @aayush105, Updated output video, Please review it.

Add the output video in description, here itself. @gurramtejaswini

**Comment by gurramtejaswini** [comment]
https://github.com/user-attachments/assets/cada33aa-dac2-430d-bfb9-5cc2fef50e6d

**Review by aayush105 — APPROVED** [review]
Ok, LGTM!!

**Comment by gurramtejaswini** [comment]
Thank you @aayush105

**Pull request merged**
