### PR TITLE
Cards Components Added by Anoop Kumar

### PR DESCRIPTION
**Pull request by daichianoop**
Adding Cards Folder containing various types of cards using CSS only

### CODE REVIEW

**Comment by daichianoop** [comment]
adding cards folder

**Review by aayush105 — COMMENTED** [review]
@daichianoop can you add the demo video or image or your project in the description section and also add in the Cards/images section so that it will be easier to see it and add in the landing page.

**Comment by daichianoop** [comment]
Ok

**Review by aayush105 — APPROVED** [review]
LGTM!! @daichianoop

**Pull request merged**
