### PR TITLE
Adding Toggle Functionality

### PR DESCRIPTION
**Pull request by Ojas-Arora**
@aayush105 I have added the Toggle Functionality to the Main Page. Kindly review this.

https://github.com/user-attachments/assets/b935731a-13fd-4f45-a4ea-552acfb3aa46

### CODE REVIEW

**Review by aayush105 — CHANGES_REQUESTED** [review]
@Ojas-Arora you only made the theme work on the background part, it should also be working inside the container as well. Also choose the theme color wisely with matching text-color and other bg color.

**Comment by Ojas-Arora** [comment]
@aayush105 I have made the required changes so that nw toggle works inside the table also.

**Comment by aayush105** [comment]
> @aayush105 I have made the required changes so that nw toggle works inside the table also.

Please provide the output demo after the re changes. @Ojas-Arora

**Comment by Ojas-Arora** [comment]
https://github.com/user-attachments/assets/076cbd64-6815-4f96-9312-5686fd37e6a7

**Review by aayush105 — APPROVED** [review]
LGTM !! @Ojas-Arora

**Pull request merged**
