### PR TITLE
Added a Clock Using HTML CSS AND JS WITH NEW TECHNOLOGY 

### PR DESCRIPTION
**Pull request by AnamuddinAhmad**

### CODE REVIEW

**Review by aayush105 — APPROVED** [review]
Can you add the video sample for this code.

**Comment by aayush105** [comment]
@AnamuddinAhmad  you can just drag and drop the video from your PC into the comment section.

**Comment by AnamuddinAhmad** [comment]
https://github.com/you-dont-need/You-Dont-Need-JavaScript/assets/119073478/76aea56e-5c9a-40d5-a4d1-6ca8a8201c47

https://github.com/you-dont-need/You-Dont-Need-JavaScript/assets/119073478/4f1b1391-1778-4976-8546-386f5ac69c41

@aayush105  Sir please check.
and merge with hacktoberfest label.

**Review by aayush105 — APPROVED** [review]
Thank you for contributing @AnamuddinAhmad . keep Contributing.

**Pull request merged**
