### PR TITLE
3d hand loader

### PR DESCRIPTION
**Pull request by aayush105**
This is the output of the code.

[3d-hand_loader.webm](https://github.com/you-dont-need/You-Dont-Need-JavaScript/assets/115408327/9daabb80-567f-447e-b2e8-6b7d7214b9b1)

### CODE REVIEW

**Comment by aayush105** [comment]
Please review this @stevemao  and merge it with hactoberfest tag.

**Comment by stevemao** [comment]
@aayush105 FYI I have added you to the team. welcome!

**Comment by stevemao** [comment]
you can review PRs and merge them yourself. Cheers

**Comment by aayush105** [comment]
Can you review thiss and merge it @stevemao , because i don't want to merge my own PRs.

**Comment by stevemao** [comment]
Please merge your own prs in the future as I may not be able to review them

**Comment by aayush105** [comment]
> Please merge your own prs in the future as I may not be able to review them

@stevemao I can't merge my own PRs sadly as i don't have permission of merging my own PRs.

**Comment by stevemao** [comment]
I just updated the role. hopefully you can do it

**Comment by aayush105** [comment]
> I just updated the role. hopefully you can do it

Thank you @stevemao. I will check it later after creating PR.

**Pull request merged**
