### PR TITLE
Carousel effect feature

### PR DESCRIPTION
**Pull request by amrutha-m206**
I have added a carousel effect feature assigned for the issue i raised .

Issue #681 

The effect has 3 pictures which changes automatically one after the other after few seconds and also you can navigate using the navigation button on the bottom of the picture.

https://github.com/user-attachments/assets/406e5549-4727-4f33-b6bc-1878b0d50e0b

### CODE REVIEW

**Comment by amrutha-m206** [comment]
i hope this is fine , is there anything else i have to change?

**Comment by amrutha-m206** [comment]
> Move that demo video folder in your main carousel folder where the other files are present. Make a output folder under your main carousel folder and add that demo video. @amrutha-m206

done i completed this 

image

**Comment by aayush105** [comment]
OK it fine now. 
Thank you @amrutha-m206 for your time and contribution.

**Comment by amrutha-m206** [comment]
thank you!

**Pull request merged**
