### PR TITLE
Updated landing page

### PR DESCRIPTION
**Pull request by ArjunCodess**
Reorganized and updated content and projects, improved layout, added categories for better user experience, and made the landing page responsive.

## Changes
- Reorganized content into categories: 3D and Animations, CSS Art, Layout and Components, Websites and Projects, Miscellaneous, Examples, V2, Misc, and Other
- Improved table layout for better readability
- Added new dark/light mode toggle button with better styling
- Added new "working" to various CSS examples and projects
- Improved responsive design for mobile devices

Demo Image and Video:
image
image
https://github.com/user-attachments/assets/8f02b6f7-4d16-43b1-bb81-5b0825028fe8

Please review and let me know if any further changes are needed.

### CODE REVIEW

**Review by aayush105 — COMMENTED** [review]
@ArjunCodess there is conflict in you PR can you resolve it? By pulling the main branch locally and then go the conflict file and select the accept incoming changes" and again push your code to the same PR.

**Comment by ArjunCodess** [comment]
Hey! I think there is some problem here.

image

If I accept the changes and push it back again, it would result in something like this:

image
(i.e. repeating the stuff I already wrote the code for)

---

Please review the changes again and sorry, if that's on me.

**Comment by aayush105** [comment]
> Hey! I think there is some problem here.
> 
> image
> If I accept the changes and push it back again, it would result in something like this:
> 
> image (i.e. repeating the stuff I already wrote the code for)
> Please review the changes again and sorry, if that's on me.

do you have the copy of your previous code? where you have made the changes? if yes then close this PR and and firstly update you branch in you forked repo, and re clone the forked repo and than make changes in the index.html file which you had done and create a PR again. Can you do it? @ArjunCodess

**Comment by ArjunCodess** [comment]
There isn't a need to open another PR.
I have updated my fork and the index.html file with the newly added projects.
This is perfect now.

Please review the changes again.

**Comment by aayush105** [comment]
> There isn't a need to open another PR. I have updated my fork and the index.html file with the newly added projects. This is perfect now.
> 
> Please review the changes again.

image

there is still a conflict, so in order to solve this issue i have told you to follow the above steps which is easier one, but you can also do it in another way by merging the the incoming changes which you can google it or use chat gpt.

**Comment by ArjunCodess** [comment]
@aayush105 Can you go here and delete this PR, please?

https://support.github.com/contact?flow=pr_removal&subject=Delete%20Pull%20Request&tags=rr-remove-data
link of the pr: https://github.com/you-dont-need/You-Dont-Need-JavaScript/pull/498

**Pull request closed without merging**
