### PR TITLE
Added CSS Table Representation

### PR DESCRIPTION
**Pull request by vinayaksoni1729**

### CODE REVIEW

**Review by aayush105 — COMMENTED** [review]
@vinayaksoni1729 resolve the conflict, others are fine.

**Comment by aayush105** [comment]
> @aayush105 Done

conflict arise please resolve this and push it again.

**Comment by vinayaksoni1729** [comment]
@aayush105 Done check!

**Review by aayush105 — APPROVED** [review]
LGTM!
Thank you @vinayaksoni1729 for contributing.

**Pull request merged**
