### PR TITLE
Added Debit card hover effect

### PR DESCRIPTION
**Pull request by Saipradyumnagoud**
#hacktoberfest24

### CODE REVIEW

**Comment by Saipradyumnagoud** [comment]
@aayush105  please Merge the PR under Hacktoberfest 24

**Comment by Saipradyumnagoud** [comment]
image

image

**Comment by aayush105** [comment]
> image
> 
> image
> 
> @aayush105 here is the Output image

Add these output under you project folder as well.
@Saipradyumnagoud

**Comment by Saipradyumnagoud** [comment]
@aayush105 i have updated the files please review the PR

**Comment by aayush105** [comment]
> @aayush105 i have updated the files please review the PR

Great work!! @Saipradyumnagoud

**Comment by Saipradyumnagoud** [comment]
@aayush105 Please Give hacktober fest label

**Comment by aayush105** [comment]
> @aayush105 Please Give hacktober fest label

Done @Saipradyumnagoud

**Pull request merged**
