### PR TITLE
Adding website fully based on HTML CSS

### PR DESCRIPTION
**Pull request by Garv0504**
I have added a user friendly website which can demonstrate the power of the fundamental units of web development i.e. HTML and CSS. The website is based on house rentals and home loans.

Page 1
Page 2
Page 3

### CODE REVIEW

**Review by aayush105 — CHANGES_REQUESTED** [review]
remove the github/workflow for the jekyll, its not necessary. @Garv0504 and again commit in the same pr

**Comment by Garv0504** [comment]
sure I will make the changes soon.

**Comment by Garv0504** [comment]
I have successfully removed the Jekyll github paging functionality.

**Review by aayush105 — APPROVED** [review]
LGTM!!!

**Pull request merged**
