### PR TITLE
make responsive animated button's section

### LINKED ISSUE #280: make responsive animated buttons below 492px
hello,
make responsive animated buttons below 492px  or small device 
Screenshot_2023-10-21_00-49-45

### PR DESCRIPTION
**Pull request by techmannih**
Issue #280 
close #280 
make responsive animated button's section for small devices below 492px 
check it and merged this PR

### CODE REVIEW

**Review by aayush105 — COMMENTED** [review]
@techmannih Add the output in the description,image section and README.md.

**Comment by techmannih** [comment]
@aayush105 
This issue and pr only make responsive of animated button section

**Comment by techmannih** [comment]
If You want to Add the output in the description,image section and README.md.
I will raise another issue and PR

**Comment by aayush105** [comment]
> If You want to Add the output in the description,image section and README.md. I will raise another issue and PR

NO need to raise another issue just add the image of the output in the image section and README.md, you can push in the same PR.

**Pull request closed without merging**
