### PR TITLE
Modified Business-Card

### PR DESCRIPTION
**Pull request by anisha-singhal**
I changed the UI of the Business-Card

### CODE REVIEW

**Comment by aayush105** [comment]
Show the before and after changes of your code.

**Comment by anisha-singhal** [comment]
> Show the before and after changes of your code.

//Before
Screenshot 2024-10-15 155632

//After - i have added animations as well
Screenshot 2024-10-15 160015

**Comment by anisha-singhal** [comment]
Please accept

**Comment by aayush105** [comment]
LGTM!!

**Pull request merged**
